In [1]:
import numpy as np

In [4]:
arr = [1,2,3,4,5,6]
ar = np.array(arr)
ar

array([1, 2, 3, 4, 5, 6])

In [14]:
arr = np.array([[1,2,3,4,5,6]])

In [15]:
arr[0,1]

2

In [16]:
arr.shape

(1, 6)

In [17]:
arr.dtype

dtype('int64')

In [18]:
arr


array([[1, 2, 3, 4, 5, 6]])

In [20]:
arr[0,2]=6

In [21]:
arr

array([[1, 2, 6, 4, 5, 6]])

In [ ]:
list_array