In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:

data=pd.DataFrame({'A': ['Yes','Yes','Crow','20',10], 'B': ['No','Yes','Pigeon','5',2.5],'C': ['Yes','No','Parrot','10',2.5],'D': ['Yes','Yes','Crow','20',10],'E': ['Yes','Yes','Pigeon','20',7.5], 'F': ['No','Yes','Hen','15',2.5],'G': ['Yes','No','Parrot','10',2.5], 'H': ['No','No','Pigeon','5',0],'I': ['No','No','Pigeon','20',2.5],'J': ['No','Yes','Crow','20',7.5],'K': ['No','No','Crow','10',2.5], 'L': ['No','No','Pigeon','15',0],'M': ['Yes','No','Parrot','20',5],'N': ['Yes','Yes','Parrot','20',7.5],'O': ['No','No','Hen','20',2.5], 'P': ['No','No','Crow','20',5],'Q': ['No','No','Parrot','10',0],'R': ['Yes','Yes','Crow','5',7.5],'S': ['No','No','Crow','20',5], 'T': ['No','No','Hen','15',0],'U': ['Yes','Yes','Hen','20',7.5], 'V': ['No','Yes','Pigeon','20',7.5],'W': ['Yes','Yes','Parrot','15',5],'X': ['Yes','Yes','Crow','20',10], 'Y': ['No','Yes','Pigeon','5',2.5],'Z': ['Yes','No','Crow','10',5],"Correct_Ans": ['Yes','Yes','Crow','20',10]},index=["Age","Eng","Bird","Sal_Inc","Marks"])

df=data.T
df
data

A       B       C     D       E    F       G       H       I  \
Age       Yes      No     Yes   Yes     Yes   No     Yes      No      No   
Eng       Yes     Yes      No   Yes     Yes  Yes      No      No      No   
Bird     Crow  Pigeon  Parrot  Crow  Pigeon  Hen  Parrot  Pigeon  Pigeon   
Sal_Inc    20       5      10    20      20   15      10       5      20   
Marks      10     2.5     2.5    10     7.5  2.5     2.5       0     2.5   

            J  ...     R     S    T    U       V       W     X       Y     Z  \
Age        No  ...   Yes    No   No  Yes      No     Yes   Yes      No   Yes   
Eng       Yes  ...   Yes    No   No  Yes     Yes     Yes   Yes     Yes    No   
Bird     Crow  ...  Crow  Crow  Hen  Hen  Pigeon  Parrot  Crow  Pigeon  Crow   
Sal_Inc    20  ...     5    20   15   20      20      15    20       5    10   
Marks     7.5  ...   7.5     5    0  7.5     7.5       5    10     2.5     5   

        Correct_Ans  
Age             Yes  
Eng             Yes  
Bird           Crow  
Sal_Inc          20  
Marks            10  

[5 rows x 27 columns]

In [3]:

df.Age[df.Age == 'Yes'] = 1
df.Age[df.Age == 'No'] = 0
df.Eng[df.Eng == 'Yes'] = 1
df.Eng[df.Eng == 'No'] = 0

df.Bird[df.Bird == 'Crow'] = 2
df.Bird[df.Bird == 'Pigeon'] = 3
df.Bird[df.Bird == 'Parrot'] = 4
df.Bird[df.Bird == 'Hen'] = 5
df


Age Eng Bird Sal_Inc Marks
A             1   1    2      20    10
B             0   1    3       5   2.5
C             1   0    4      10   2.5
D             1   1    2      20    10
E             1   1    3      20   7.5
F             0   1    5      15   2.5
G             1   0    4      10   2.5
H             0   0    3       5     0
I             0   0    3      20   2.5
J             0   1    2      20   7.5
K             0   0    2      10   2.5
L             0   0    3      15     0
M             1   0    4      20     5
N             1   1    4      20   7.5
O             0   0    5      20   2.5
P             0   0    2      20     5
Q             0   0    4      10     0
R             1   1    2       5   7.5
S             0   0    2      20     5
T             0   0    5      15     0
U             1   1    5      20   7.5
V             0   1    3      20   7.5
W             1   1    4      15     5
X             1   1    2      20    10
Y             0   1    3       5   2.5
Z             1   0    2      10     5
Correct_Ans   1   1    2      20    10

In [4]:
x=df.iloc[0:30,0:4].values
y=df.iloc[:,-1].values
y.reshape(-1,1)
x.reshape(-1,1)
x

array([[1, 1, 2, '20'],
       [0, 1, 3, '5'],
       [1, 0, 4, '10'],
       [1, 1, 2, '20'],
       [1, 1, 3, '20'],
       [0, 1, 5, '15'],
       [1, 0, 4, '10'],
       [0, 0, 3, '5'],
       [0, 0, 3, '20'],
       [0, 1, 2, '20'],
       [0, 0, 2, '10'],
       [0, 0, 3, '15'],
       [1, 0, 4, '20'],
       [1, 1, 4, '20'],
       [0, 0, 5, '20'],
       [0, 0, 2, '20'],
       [0, 0, 4, '10'],
       [1, 1, 2, '5'],
       [0, 0, 2, '20'],
       [0, 0, 5, '15'],
       [1, 1, 5, '20'],
       [0, 1, 3, '20'],
       [1, 1, 4, '15'],
       [1, 1, 2, '20'],
       [0, 1, 3, '5'],
       [1, 0, 2, '10'],
       [1, 1, 2, '20']], dtype=object)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.32, random_state=5)

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
lr.score(X_test,y_test)


0.9247122327543182

In [9]:
lr.score(X_train,y_train)



0.9460774011863419

In [10]:

lr.predict([[1,2,4,20]])


array([9.88713203])

In [11]:
from sklearn.tree import DecisionTreeRegressor


In [12]:
DT=DecisionTreeRegressor()
DT.fit(X_train,y_train)


DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [13]:
DT.score(X_test,y_test)

0.9488636363636364

In [14]:
DT.score(X_train,y_train)


1.0

In [15]:
DT.predict([[1,1,1,20]])

array([10.])

In [16]:
from sklearn.ensemble import GradientBoostingRegressor

In [17]:
br=GradientBoostingRegressor()

In [18]:
br.fit(X_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [19]:
br.score(X_test,y_test)


0.9885851165460521

In [21]:
br.predict([[1,2,4,20]])

array([7.49889066])

In [22]:
y_true=br.predict(X_test)

In [23]:
print(y_test)
print(y_true)


[10 0 2.5 0 7.5 2.5 5 10 2.5]
[9.99125883 0.26485477 2.50154454 0.61166909 7.07063164 3.37287396
 4.94455893 9.99125883 2.53701676]


In [24]:
df.describe()

Age  Eng  Bird Sal_Inc  Marks
count    27   27    27      27   27.0
unique    2    2     4       4    5.0
top       0    1     2      20    2.5
freq     14   14    10      14    8.0

In [25]:
Rank_1=df[df['Marks']==10]
Rank_2=df[df['Marks']==7.5]
Rank_3=df[df['Marks']==5]
Rank_4=df[df['Marks']==2.5]

In [26]:
print("Ranking 1")
print(Rank_1)
print(" ")
print("Ranking 2")
print(Rank_2)
print(" ")
print("Ranking 3")
print(Rank_3)
print(" ")
print("Ranking 4")
print(Rank_4)

Ranking 1
            Age Eng Bird Sal_Inc Marks
A             1   1    2      20    10
D             1   1    2      20    10
X             1   1    2      20    10
Correct_Ans   1   1    2      20    10
 
Ranking 2
  Age Eng Bird Sal_Inc Marks
E   1   1    3      20   7.5
J   0   1    2      20   7.5
N   1   1    4      20   7.5
R   1   1    2       5   7.5
U   1   1    5      20   7.5
V   0   1    3      20   7.5
 
Ranking 3
  Age Eng Bird Sal_Inc Marks
M   1   0    4      20     5
P   0   0    2      20     5
S   0   0    2      20     5
W   1   1    4      15     5
Z   1   0    2      10     5
 
Ranking 4
  Age Eng Bird Sal_Inc Marks
B   0   1    3       5   2.5
C   1   0    4      10   2.5
F   0   1    5      15   2.5
G   1   0    4      10   2.5
I   0   0    3      20   2.5
K   0   0    2      10   2.5
O   0   0    5      20   2.5
Y   0   1    3       5   2.5
