In [2]:
import tensorflow.compat.v1 as tf


In [3]:
tf.__version__

'1.13.2'

In [9]:
hello = tf.constant("Hello")

In [10]:
hello

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [11]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [12]:
world = tf.constant("world")

In [13]:
tresultype(world)

tensorflow.python.framework.ops.Tensor

In [15]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [16]:
result

b'Helloworld'

In [17]:
var1 = tf.constant(10)
var2 = tf.constant(30)

In [18]:
var1 

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

In [19]:
var1 + var2

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [20]:
with tf.Session() as sess:
    result = sess.run(var1 + var2)

In [21]:
result

40

In [22]:
const = tf.constant(10)

In [23]:
mat_1 = tf.fill((5,5),10)

In [24]:
zeros = tf.zeros((4,4))

In [25]:
ones = tf.ones((4,4))

In [30]:
random = tf.random_normal((4,4),mean=0,stddev=1.0)

In [32]:
randomu =  tf.random_uniform((4,4),minval=0, maxval=1)

In [33]:
myops = [const,mat_1,zeros,ones,random,randomu]

In [34]:
sess = tf.InteractiveSession()

In [36]:
for operation in myops:
    print(sess.run(operation))
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.4664776   1.5969316   1.4075719   1.6153377 ]
 [ 1.0267287   0.1411551   0.45526525  0.10487425]
 [-0.77685565 -0.0467082   1.5369936  -1.4360886 ]
 [-0.10370451 -1.6247983  -0.00834247 -0.48161173]]


[[0.7319087  0.8114331  0.97697663 0.6483313 ]
 [0.18469727 0.23400056 0.949571   0.63301253]
 [0.79556453 0.41658175 0.37681556 0.8745527 ]
 [0.78646946 0.8241873  0.40840864 0.8595443 ]]




In [37]:
for operation in myops:
    print(operation.eval())
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.25195867 -0.7097602  -1.6694927   1.6280264 ]
 [ 0.23256023 -0.7002804   0.9125759  -1.3556755 ]
 [ 0.27501604 -0.70362407 -1.1852422   1.3218638 ]
 [-0.48022637 -0.20918915 -0.6070282  -1.0672036 ]]


[[0.05199945 0.3114015  0.9266753  0.5052819 ]
 [0.12565386 0.09160256 0.45855057 0.06342661]
 [0.9262564  0.31057537 0.14205742 0.3209256 ]
 [0.66446257 0.41532576 0.02935934 0.7724247 ]]




In [38]:
a = tf.constant([[1,2],[3,4]])

In [39]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [40]:
b = tf.constant([[10],[100]])

In [41]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [42]:
result = tf.matmul(a,b)

In [45]:
sess.run(result)

array([[210],
       [430]], dtype=int32)